
import { Tool, Category } from './types';

export const categories: Category[] = [
  { id: 'pessoas', name: 'Pessoas & Identidades', icon: '👤' },
  { id: 'fake-data', name: 'Geradores de Dados Falsos', icon: '🎭' },
  { id: 'contato', name: 'Comunicação Temporária', icon: '📱' },
  { id: 'judicial', name: 'Justiça & Processos', icon: '⚖️' },
  { id: 'governo', name: 'Governo & Transparência', icon: '🏛️' },
  { id: 'social-br', name: 'Benefícios Sociais', icon: '🧾' },
  { id: 'geo', name: 'Mapas & Geoespacial', icon: '🗺️' },
  { id: 'transporte', name: 'Transporte & Veículos', icon: '🚗' },
  { id: 'busca', name: 'Motores de Busca', icon: '🔍' },
  { id: 'dorking', name: 'Google Hacking (Dorks)', icon: '🕵️' },
  { id: 'telecom', name: 'Telecom & Celulares', icon: '📡' },
  { id: 'academico', name: 'Acadêmico & Livros', icon: '🎓' },
  { id: 'saude', name: 'Saúde & Vigilância', icon: '🏥' },
  { id: 'empresas', name: 'Empresas & Propriedades', icon: '🏢' },
  { id: 'ciber', name: 'Segurança & Ciber', icon: '🛡️' },
  { id: 'web', name: 'Arquivos da Web', icon: '🏛️' },
  { id: 'sandbox', name: 'Sandbox & Emuladores', icon: '📦' },
  { id: 'produtividade', name: 'Produtividade & Extração', icon: '⚡' },
  { id: 'hashes', name: 'Hashes & Criptografia', icon: '🔑' },
  { id: 'downloader', name: 'Downloaders & Extratores', icon: '📥' },
];

export const tools: Tool[] = [
  // --- CONTATO TEMPORÁRIO / DESCARTÁVEL ---
  { id: 'c1', name: 'Onlinesim.net', url: 'https://onlinesim.net', description: 'Número de telefone temporário para recebimento de SMS.', category: 'contato', source: '4ALL' },
  { id: 'c2', name: 'DoNotPay', url: 'https://donotpay.com', description: 'Número de telefone temporário e proteção legal.', category: 'contato', source: '4ALL' },
  { id: 'c3', name: 'VoIPSuite', url: 'https://www.voipsuite.com/guide', description: 'Guia completo de suíte VoIP para investigadores.', category: 'contato', source: '4ALL' },
  { id: 'c4', name: 'Twilio CLI Guide', url: 'https://www.twilio.com/docs/usage/tutorials/how-to-use-twilio-cli', description: 'Uso de CLI do Twilio para OSINT.', category: 'contato', source: '4ALL' },
  { id: 'c5', name: '10minutemail.com', url: 'https://10minutemail.com', description: 'Caixa de correio temporária de 10 minutos.', category: 'contato', source: '4ALL' },
  { id: 'c6', name: 'AnonAddy', url: 'https://anonaddy.com', description: 'E-mail descartável com aliases ilimitados.', category: 'contato', source: '4ALL' },
  { id: 'c7', name: 'SimpleLogin', url: 'https://simplelogin.io', description: 'Aliases de e-mail avançados para privacidade.', category: 'contato', source: '4ALL' },
  { id: 'c8', name: 'MailDrop', url: 'https://maildrop.cc', description: 'Caixa de correio temporária rápida.', category: 'contato', source: '4ALL' },
  { id: 'c9', name: 'Send text free', url: 'https://sendtextfree.com', description: 'Envio de SMS gratuito via web.', category: 'contato', source: '4ALL' },
  { id: 'c10', name: 'SendaText', url: 'https://sendatext.net', description: 'Plataforma para envio de mensagens de texto.', category: 'contato', source: '4ALL' },
  { id: 'c11', name: 'Receive SMS Online', url: 'https://receive-sms-online.info', description: 'Números públicos para receber SMS.', category: 'contato', source: '4ALL' },
  { id: 'c12', name: 'Receive SMS Online FREE', url: 'https://receive-sms-online-free.com', description: 'Receba códigos de verificação por SMS.', category: 'contato', source: '4ALL' },
  { id: 'c13', name: 'Smstome.com', url: 'https://smstome.com', description: 'Receba SMS online gratuitamente.', category: 'contato', source: '4ALL' },
  { id: 'c14', name: 'Free Fax', url: 'https://freefax.com', description: 'Envio de fax online gratuito.', category: 'contato', source: '4ALL' },
  { id: 'c15', name: 'Amazon SNS', url: 'https://aws.amazon.com/sns', description: 'Serviço de notificação push e SMS.', category: 'contato', source: '4ALL' },
  { id: 'c16', name: 'Twilio', url: 'https://twilio.com', description: 'APIs de comunicação profissional.', category: 'contato', source: '4ALL' },
  { id: 'c17', name: 'One-time Mobile', url: 'https://onetime-mobile.osintstash.com', description: 'Números móveis descartáveis por OsintStash.', category: 'contato', source: '4ALL' },
  { id: 'c18', name: 'Receive SMS Online For Free', url: 'https://receivesmsonlineforfree.com', description: 'Recebimento de SMS sem registro.', category: 'contato', source: '4ALL' },

  // --- GERADOR DE IDENTIDADES ---
  { id: 'fd0', name: 'ID GENERATOR', url: 'https://id-generator.com', description: 'Gerador universal de IDs fictícios.', category: 'fake-data', source: '4ALL' },
  { id: 'fd1', name: 'Username Generator', url: 'https://username-generator.org', description: 'Gerador de nomes de usuário seguros.', category: 'fake-data', source: '4ALL' },
  { id: 'fd2', name: 'Fake Name Generator', url: 'https://fakenamegenerator.com', description: 'Identidades completas fictícias.', category: 'fake-data', source: '4ALL' },
  { id: 'fd3', name: 'Resume Generator', url: 'https://resume-generator.com', description: 'Cria currículos profissionais fictícios.', category: 'fake-data', source: '4ALL' },
  { id: 'fd4', name: 'International Name Gen', url: 'https://international-name-generator.com', description: 'Nomes aleatórios internacionais.', category: 'fake-data', source: '4ALL' },
  { id: 'fd5', name: 'IMEI Gen (Windows Phone)', url: 'https://imei-generator.com/windows-phone', description: 'Gerador de IMEI para WP.', category: 'fake-data', source: '4ALL' },
  { id: 'fd6', name: 'IMEI Number Generator', url: 'https://imei-generator.com', description: 'Gerador de números IMEI genérico.', category: 'fake-data', source: '4ALL' },
  { id: 'fd7', name: 'US ID Generator (All)', url: 'https://us-id-generator.com', description: 'SSN, Driver License e Tax ID.', category: 'fake-data', source: '4ALL' },
  { id: 'fd8', name: 'WA Driver License Gen', url: 'https://washington-drivers-license-generator.com', description: 'Gerador de CNH de Washington.', category: 'fake-data', source: '4ALL' },
  { id: 'fd9', name: 'Fake Drivers License Gen', url: 'https://fake-drivers-license-generator.com', description: 'Gerador de habilitação fictícia.', category: 'fake-data', source: '4ALL' },
  { id: 'fd10', name: 'This Rental Does Not Exist', url: 'https://thisrentaldoesnotexist.com', description: 'Simulação de aluguéis via IA.', category: 'fake-data', source: '4ALL' },
  { id: 'fd11', name: 'Face Photo Generator', url: 'https://face-photo-generator.com', description: 'Gera rostos realistas (thispersondoesnotexist).', category: 'fake-data', source: '4ALL' },
  { id: 'fd12', name: 'Random Face Generator', url: 'https://randomfacegenerator.com', description: 'Outro gerador de rostos via IA.', category: 'fake-data', source: '4ALL' },
  { id: 'fd13', name: 'Credit Card Generator', url: 'https://creditcard-generator.com', description: 'Gera números de cartão de crédito válidos para testes.', category: 'fake-data', source: '4ALL' },
  { id: 'fd14', name: 'SIN Generator', url: 'https://sin-generator.com', description: 'Seguro social canadense fictício.', category: 'fake-data', source: '4ALL' },
  { id: 'fd15', name: 'ABA Generator', url: 'https://aba-generator.com', description: 'Gerador de roteamento bancário.', category: 'fake-data', source: '4ALL' },
  { id: 'fd16', name: 'VIN Generator', url: 'https://vin-generator.com', description: 'Identificação de veículos.', category: 'fake-data', source: '4ALL' },
  { id: 'fd17', name: 'NINO Generator', url: 'https://nino-generator.com', description: 'ID britânico fictício.', category: 'fake-data', source: '4ALL' },
  { id: 'fd18', name: 'SSN Generator', url: 'https://ssn-generator.com', description: 'Seguro social americano fictício.', category: 'fake-data', source: '4ALL' },
  { id: 'fd19', name: 'IID Generator (G. Bunin)', url: 'https://iid-generator.georgybunin.com', description: 'Identidade Internacional de Georgy Bunin.', category: 'fake-data', source: '4ALL' },
  { id: 'fd20', name: 'GUID/UUID Generator', url: 'https://guid-generator.com', description: 'Identificadores únicos.', category: 'fake-data', source: '4ALL' },
  { id: 'fd21', name: 'Nano ID CC', url: 'https://nanoid-cc.com', description: 'Gerador de identificadores compactos.', category: 'fake-data', source: '4ALL' },
  { id: 'fd22', name: 'Generate SA ID Numbers', url: 'https://sa-id-generator.com', description: 'Identidades da África do Sul.', category: 'fake-data', source: '4ALL' },
  { id: 'fd23', name: 'SSN Decoder', url: 'https://ssn-decoder.com', description: 'Decodificação de lógica de SSN.', category: 'fake-data', source: '4ALL' },
  { id: 'fd24', name: 'Drivers License Decoder', url: 'https://drivers-license-decoder.com', description: 'Decodificação de habilitação.', category: 'fake-data', source: '4ALL' },
  { id: 'fd25', name: 'Dating Profile Gen', url: 'https://dating-profile-generator.com', description: 'Cria perfis de apps de namoro.', category: 'fake-data', source: '4ALL' },
  { id: 'fd26', name: 'Fake Identity Generator', url: 'https://fake-identity-generator.com', description: 'Identidade rápida e completa.', category: 'fake-data', source: '4ALL' },
  { id: 'fd27', name: 'Fake Company Gen', url: 'https://fake-company-generator.com', description: 'Nomes de empresas aleatórios.', category: 'fake-data', source: '4ALL' },
  { id: 'fd28', name: 'Twitter Profile Gen', url: 'https://twitter-profile-generator.com', description: 'Simula perfis reais do Twitter.', category: 'fake-data', source: '4ALL' },
  { id: 'fd29', name: 'TikTok Profile Gen', url: 'https://fake-tiktok-profile-generator.com', description: 'Simula perfis do TikTok.', category: 'fake-data', source: '4ALL' },
  { id: 'fd30', name: 'YouTube Channel Gen', url: 'https://fake-youtube-channel-generator.com', description: 'Cria canais fictícios.', category: 'fake-data', source: '4ALL' },
  { id: 'fd31', name: 'Resume Builder', url: 'https://resume-builder.com', description: 'Construtor de currículos online.', category: 'fake-data', source: '4ALL' },
  { id: 'fd32', name: 'Fake Generator Tools', url: 'https://fake-generator-tools.com', description: 'Conjunto completo de ferramentas falsas.', category: 'fake-data', source: '4ALL' },

  // --- BUSCAS UNIFICADAS E MOTORES ---
  { id: 'b1', name: 'IntelTechniques OSINT', url: 'https://inteltechniques.com/osint', description: 'A maior suite de ferramentas OSINT do mundo.', category: 'busca', source: '4ALL' },
  { id: 'b2', name: 'SynapsInt', url: 'https://synapsint.com', description: 'Agregador de múltiplas fontes OSINT.', category: 'busca', source: '4ALL' },
  { id: 'b3', name: 'InfoTracer', url: 'https://infotracer.com', description: 'Rastreador profissional de informações públicas.', category: 'busca', source: '4ALL' },
  { id: 'b4', name: 'MetaDefender', url: 'https://metadefender.com', description: 'Análise de segurança em arquivos e IPs.', category: 'busca', source: '4ALL' },
  { id: 'b5', name: 'Username Search', url: 'https://username-search.com', description: 'Busca unificada de nomes de usuário.', category: 'busca', source: '4ALL' },
  { id: 'b6', name: 'SpyTox', url: 'https://spytox.com', description: 'Informações profundas de pessoas.', category: 'busca', source: '4ALL' },
  { id: 'b7', name: 'Effect Group', url: 'https://effectgroup.io', description: 'Busca integrada e avançada.', category: 'busca', source: '4ALL' },
  { id: 'b8', name: 'osrframework', url: 'https://osrframework.com', description: 'Framework profissional de reconhecimento.', category: 'busca', source: '4ALL' },
  { id: 'b9', name: 'Google CSE', url: 'https://cse.google.com', description: 'Mecanismo de busca customizado.', category: 'busca', source: '4ALL' },
  { id: 'b10', name: 'OSINT Search Engine', url: 'https://osint-search-engine.com', description: 'Motor de busca específico para investigadores.', category: 'busca', source: '4ALL' },
  { id: 'b11', name: 'LinkScope', url: 'https://linkscope.io', description: 'Análise e visualização de links externos.', category: 'busca', source: '4ALL' },
  { id: 'b12', name: 'Criminal IP', url: 'https://criminalip.io', description: 'Inteligência de ameaças em tempo real.', category: 'busca', source: '4ALL' },
  { id: 'b13', name: 'Google Advanced Search', url: 'https://google.com/advanced_search', description: 'Parâmetros avançados oficiais do Google.', category: 'busca', source: '4ALL' },
  { id: 'b14', name: 'MetaGer', url: 'https://metager.org', description: 'Busca protegida com privacidade alemã.', category: 'busca', source: '4ALL' },
  { id: 'b15', name: 'Brave Search', url: 'https://search.brave.com', description: 'Motor de busca independente e focado em privacidade.', category: 'busca', source: '4ALL' },
  { id: 'b16', name: 'Million Short', url: 'https://millionshort.com', description: 'Remove os resultados óbvios para achar o oculto.', category: 'busca', source: '4ALL' },
  { id: 'b17', name: 'CachedViews.com', url: 'https://cachedviews.com', description: 'Busca de páginas em cache (Google/Coral/Archive).', category: 'busca', source: '4ALL' },
  { id: 'b18', name: 'Sploitus', url: 'https://sploitus.com', description: 'Motor de busca para exploits.', category: 'busca', source: '4ALL' },

  // --- PESQUISA DE PESSOAS ---
  { id: 'ps1', name: 'IDCrawl', url: 'https://idcrawl.com', description: 'Busca de pessoas em toda a web.', category: 'pessoas', source: '4ALL' },
  { id: 'ps2', name: 'WebMii', url: 'https://webmii.com', description: 'Visibilidade online e pontuação de perfil.', category: 'pessoas', source: '4ALL' },
  { id: 'ps3', name: 'TruePeopleSearch', url: 'https://truepeoplesearch.com', description: 'Rastreador de registros públicos gratuito.', category: 'pessoas', source: '4ALL' },
  { id: 'ps4', name: 'Free People Search', url: 'https://freepeoplesearch.com', description: 'Busca simples de registros.', category: 'pessoas', source: '4ALL' },
  { id: 'ps5', name: 'Fast People Search', url: 'https://fastpeoplesearch.com', description: 'Encontra telefone e endereço rapidamente.', category: 'pessoas', source: '4ALL' },
  { id: 'ps6', name: 'Yandex People Search', url: 'https://yandex.com/people', description: 'Busca de pessoas do ecossistema russo.', category: 'pessoas', source: '4ALL' },
  { id: 'ps7', name: 'PeekYou', url: 'https://peekyou.com', description: 'Analisa perfis sociais e notícias vinculadas.', category: 'pessoas', source: '4ALL' },
  { id: 'ps8', name: 'White Pages', url: 'https://whitepages.com', description: 'Páginas brancas profissionais.', category: 'pessoas', source: '4ALL' },
  { id: 'ps9', name: 'Canada 411', url: 'https://canada411.ca', description: 'Diretório canadense.', category: 'pessoas', source: '4ALL' },
  { id: 'ps10', name: 'TruthFinder', url: 'https://truthfinder.com', description: 'Verificação de antecedentes e registros criminais.', category: 'pessoas', source: '4ALL' },
  { id: 'ps11', name: 'ThatsThem', url: 'https://thatsthem.com', description: 'Informa e-mail e endereço baseados no nome.', category: 'pessoas', source: '4ALL' },
  { id: 'ps12', name: 'xlek', url: 'https://xlek.com', description: 'Busca profunda de registros públicos.', category: 'pessoas', source: '4ALL' },
  { id: 'ps13', name: '192', url: 'https://192.com', description: 'Especializado no Reino Unido.', category: 'pessoas', source: '4ALL' },

  // --- MAPAS E GEO ---
  { id: 'm1', name: 'Google Maps', url: 'https://maps.google.com', description: 'Referência global em mapeamento.', category: 'geo', source: '4ALL' },
  { id: 'm2', name: 'Bing Maps', url: 'https://bing.com/maps', description: 'Visualização aérea de alta qualidade da Microsoft.', category: 'geo', source: '4ALL' },
  { id: 'm3', name: 'Yandex.Maps', url: 'https://yandex.com/maps', description: 'Melhor cobertura para Rússia e Europa Oriental.', category: 'geo', source: '4ALL' },
  { id: 'm4', name: 'Panorama Generator', url: 'https://panoramagenerator.com', description: 'Cria panoramas 360 de coordenadas.', category: 'geo', source: '4ALL' },
  { id: 'm5', name: 'Mapillary', url: 'https://mapillary.com', description: 'Imagens de rua colaborativas.', category: 'geo', source: '4ALL' },
  { id: 'm6', name: 'Waze', url: 'https://waze.com', description: 'Trânsito e incidentes em tempo real.', category: 'geo', source: '4ALL' },
  { id: 'm7', name: 'Baidu Maps', url: 'https://map.baidu.com', description: 'Mapeamento detalhado da China.', category: 'geo', source: '4ALL' },
  { id: 'm8', name: 'OpenStreetMap', url: 'https://openstreetmap.org', description: 'O mapa aberto e editável por excelência.', category: 'geo', source: '4ALL' },
  { id: 'm9', name: 'Satellites.pro', url: 'https://satellites.pro', description: 'Várias fontes de satélite em um só lugar.', category: 'geo', source: '4ALL' },
  { id: 'm10', name: 'Radio Garden', url: 'https://radio.garden', description: 'Ouça rádios do mundo todo via mapa.', category: 'geo', source: '4ALL' },
  { id: 'm11', name: 'Windy', url: 'https://windy.com', description: 'Visualização meteorológica e radares mundiais.', category: 'geo', source: '4ALL' },
  { id: 'm12', name: 'KartaView', url: 'https://kartaview.com', description: 'OpenStreetView - imagens de rua livres.', category: 'geo', source: '4ALL' },
  { id: 'm13', name: 'Earth', url: 'https://earth.com', description: 'Visualização ambiental do planeta.', category: 'geo', source: '4ALL' },
  { id: 'm14', name: 'GeoNames', url: 'https://geonames.org', description: 'Base de dados geográfica massiva.', category: 'geo', source: '4ALL' },
  { id: 'm15', name: 'GeoIP Tracker', url: 'https://geoiptracker.com', description: 'Rastreador de IP baseado em geolocalização.', category: 'geo', source: '4ALL' },

  // --- BENEFÍCIOS SOCIAIS BRASIL ---
  { id: 'br1', name: 'Bolsa Família', url: 'https://www.caixa.gov.br/programas-sociais/Paginas/default.aspx', description: 'Consulta oficial de benefícios sociais.', category: 'social-br', source: 'Brazuca' },
  { id: 'br2', name: 'Auxílio Emergencial', url: 'https://consultaauxilio.cidadania.gov.br/consulta/#/', description: 'Consulta de elegibilidade de auxílios.', category: 'social-br', source: 'Brazuca' },
  { id: 'br3', name: 'Valores a Receber (BC)', url: 'https://valoresareceber.bcb.gov.br/publico/', description: 'Valores esquecidos em contas bancárias.', category: 'social-br', source: 'Brazuca' },

  // --- JUSTIÇA BRASIL ---
  { id: 'ju1', name: 'Mandados (BNMP)', url: 'https://portalbnmp.cnj.jus.br/#/pesquisa-peca#', description: 'Mandados de prisão no Brasil.', category: 'judicial', source: 'Brazuca' },
  { id: 'ju2', name: 'JusBrasil', url: 'https://www.jusbrasil.com.br/', description: 'Maior portal de consulta jurídica nacional.', category: 'judicial', source: 'Brazuca' },
  { id: 'ju3', name: 'Escavador', url: 'https://www.escavador.com/', description: 'Localização de processos por nome.', category: 'judicial', source: 'Brazuca' },

  // --- SANDBOX & EMULADORES ---
  { id: 'sb1', name: 'Kasm', url: 'https://kasmweb.com/', description: 'Streaming de navegadores e desktops seguros.', category: 'sandbox', source: '4ALL' },
  { id: 'sb2', name: 'BlueStacks', url: 'https://www.bluestacks.com/', description: 'Emulador Android focado em performance.', category: 'sandbox', source: '4ALL' },
  { id: 'sb3', name: 'Genymotion', url: 'https://www.genymotion.com/', description: 'Emulador Android para nuvem e desktop.', category: 'sandbox', source: '4ALL' },

  // --- PRODUTIVIDADE & EXTRAÇÃO ---
  { id: 'pr1', name: 'Wolfram Alpha', url: 'https://www.wolframalpha.com/', description: 'Inteligência computacional.', category: 'produtividade', source: '4ALL' },
  { id: 'pr2', name: 'DeepL Translator', url: 'https://www.deepl.com/translator', description: 'Melhor ferramenta de tradução baseada em IA.', category: 'produtividade', source: '4ALL' },
  { id: 'pr3', name: 'Start.me', url: 'https://start.me', description: 'Dashboard personalizável para investigadores.', category: 'produtividade', source: '4ALL' },
  { id: 'pr4', name: 'CyberChef', url: 'https://gchq.github.io/CyberChef/', description: 'Operações em dados e codificação.', category: 'ciber', source: '4ALL' }
];
